image: condaforge/mambaforge:22.9.0-3

tasks:
  - name: Initialize
    init: |
      . /opt/conda/etc/profile.d/conda.sh
      conda activate base
      sleep 5
      mamba create -y -n assembly-scan -c conda-forge -c bioconda 'python>=3.7' pre-commit
      conda activate assembly-scan
      mkdir -p .vscode
      echo '{"python.pythonPath": "/home/gitpod/.conda/envs/assembly-scan /bin/python"}' > .vscode/settings.json
      pre-commit install --install-hooks
    command: |
vscode:
  extensions:
    - codezombiech.gitignore                 # Language support for .gitignore files
    - davidanson.vscode-markdownlint         # Markdown/CommonMark linting and style checking for Visual Studio Code
    - eamodio.gitlens                        # Quickly glimpse into whom, why, and when a line or code block was changed
    - EditorConfig.EditorConfig              # override user/workspace settings with settings found in .editorconfig files
    - Gruntfuggly.todo-tree                  # Display TODO and FIXME in a tree view in the activity bar
    - mechatroner.rainbow-csv                # Highlight columns in csv files in different colors
    - oderwat.indent-rainbow                 # Highlight indentation level
    - streetsidesoftware.code-spell-checker  # Spelling checker for source code
    - ms-python.black-formatter              # Support for Python Black formatter
    - njpwerner.autodocstring                # Use type hints to auto create doc strings
    - github.copilot                         # Load up Copilot
    - ms-python.python                       # Syntax and linting